services:
  app:
    build: .
    image: api-gateway
    container_name: api-gateway
    ports:
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
    external: true