server:
  port: 4004 # Gateway listens on port 4004

auth:
  service:
    url: http://localhost:4005/auth-service

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.burstCapacity: 2
                redis-rate-limiter.replenishRate: 2
                key-resolver: "#{@ipKeyResolver}"
          routes:
            # Route for /auth/** to auth-service
            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            # Route for /api/patients/** to patient-service
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation

            # Route for /api/docs/patients to patient-service /v3/api-docs
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs

            # Route for /api/docs/auth to auth-service /v3/api-docs
            - id: api-docs-auth-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: gateway