spring.application.name=patient-service
server.port=4000

#Datasource
#spring.datasource.url=jdbc:postgresql://patient-service-db:5432/mydb
#spring.datasource.username=admin
#spring.datasource.password=secret
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# SQL init
spring.sql.init.mode=always


#H2 in memory database configs
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#postgres config to connect to RDS instance
spring.datasource.url=jdbc:postgresql://database-1.cbkw0eweuleq.ap-south-1.rds.amazonaws.com:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=password123#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database.platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Kafka configurations
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

#AWS S3 client config
#cloud.aws.credentials.access-key=AKIA4YV43SR75CSCBTTU
#cloud.aws.credentials.secret-key=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
cloud.aws.region.static=ap-south-1
aws.bucket.name=aws-bucket-patientmgmt

#redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
